apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-app-build
spec:
  source:
    type: Git
    git:
      uri: git@github.com:murraysh/IAC.git  # GitHub repository URL
      ref: master  # Branch to pull from
      secret:
        name: git-ssh-secret  # Reference the secret here for SSH authentication
  strategy:
    type: Docker
    dockerStrategy:
      dockerfile: Dockerfile  # Dockerfile in the root of the repository
  output:
    to:
      kind: ImageStreamTag
      name: my-app:latest  # Tag the resulting image
  triggers:
    - type: Git
    - type: ConfigChange
    - type: ImageChange
