apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-app-build
spec:
  source:
    type: Git
    git:
      uri: git@gitlab.com:username/repository.git  # GitLab SSH URL
      ref: main  # Branch to build from (adjust as needed)
      secret:
        name: gitlab-ssh-secret  # The secret containing the SSH private key
  strategy:
    type: Docker  # Docker-based build strategy
    dockerStrategy:
      dockerfile: Dockerfile  # Dockerfile name (adjust if different)
  output:
    to:
      kind: ImageStreamTag
      name: my-app:latest  # The image to push to
  triggers:
    - type: Git
      git:
        secret: <random-string>  # Optional: Set a secret for GitLab webhook integration
    - type: ConfigChange
    - type: ImageChange
